# Generated by Django 3.2 on 2021-04-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MushroomXpert_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindMushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Ai_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='image',
        ),
        migrations.AddField(
            model_name='mushroom',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='edible_choices',
            field=models.CharField(choices=[('ED', 'Edible'), ('PO', 'Poisonous'), ('NE', 'Not edible')], default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='image_url',
            field=models.URLField(default='none'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
